import Link from "next/link";
import { categories, curicartLink } from "@/lib/links";
import { articles, topics } from "@/lib/content";

export function Header() { return <header className="site-header"><Link className="wordmark" href="/">Kakobuy <span>Spreadsheet Index</span></Link><nav><Link href="/questions">Questions</Link><Link href="/topics/qc-photos">Topics</Link><Link href="/sources">Sources</Link></nav><Link className="header-cta" href="/questions">Browse answers</Link></header>; }
export function Footer() { return <footer><div><strong>Kakobuy Spreadsheet Index</strong><p>Practical answers for QC photos, product links, spreadsheets, and product research.</p></div><div className="footer-links"><Link href="/about">About</Link><Link href="/contact">Contact</Link><Link href="/privacy">Privacy</Link></div></footer>; }
export function CategoryGrid() { return <section className="category-section"><div className="section-heading"><div><p className="eyebrow">Product research</p><h2>Explore product categories</h2></div><p>Use a category view when you want product examples alongside a Kakobuy question.</p></div><div className="category-grid">{categories.map((category) => <a className={`category-card category-${category.slug}`} key={category.slug} href={curicartLink(category.path, `home_category_${category.slug}`)} rel="noreferrer"><div className="category-art" aria-hidden="true"><span>{category.icon}</span></div><strong>{category.name}</strong><small>Browse examples</small></a>)}</div></section>; }
export function ArticleCard({ article }: { article: (typeof articles)[number] }) { return <article className="article-card"><p className="card-topic">{article.topic}</p><h3><Link href={`/questions/${article.slug}`}>{article.title}</Link></h3><p>{article.quickAnswer}</p><Link className="read-link" href={`/questions/${article.slug}`}>Read answer <span aria-hidden="true">→</span></Link></article>; }
export function QuestionList({ limit }: { limit?: number }) { return <div className="article-grid">{articles.slice(0, limit).map((article) => <ArticleCard article={article} key={article.slug} />)}</div>; }
export function TopicNav() { return <section className="topic-strip"><p className="eyebrow">Browse by problem</p><div>{topics.map((topic) => <Link href={`/topics/${topic.slug}`} key={topic.slug}><strong>{topic.name}</strong><span>{topic.description}</span></Link>)}</div></section>; }
