import Link from "next/link";
import { CategoryGrid, Footer, Header, QuestionList, TopicNav } from "./components";

export default function Home() {
  return <><Header /><main>
    <section className="hero"><div><p className="eyebrow">Kakobuy research, organized</p><h1>Clear answers for the links, photos, and spreadsheets you are checking.</h1><p>Find a practical answer before you rely on a Kakobuy product link or a spreadsheet row. Each guide starts with the question, then shows what to compare and what still needs checking.</p><div className="hero-actions"><Link className="button" href="/questions">Browse questions</Link><Link className="button secondary" href="#categories">Explore categories</Link></div></div><div className="question-preview"><p>Start with a question</p><Link href="/questions/where-to-see-kakobuy-qc-photos">Where can I see Kakobuy QC photos?</Link><Link href="/questions/kakobuy-product-link-not-working">Why is my Kakobuy product link not working?</Link><Link href="/questions/choose-kakobuy-spreadsheet-with-qc-photos">How do I choose a spreadsheet with QC photos?</Link></div></section>
    <section className="content-section index-answer" aria-labelledby="find-index-answer"><div className="section-title"><h2 id="find-index-answer">How to find a Kakobuy index</h2></div><div className="notice"><p>Use this index as a starting point for Kakobuy product and spreadsheet research. Open the entry that matches your task, then check the source and visible details before relying on it.</p><ol><li>Relevance: does the entry cover the product or topic you need?</li><li>Source: is the original product or marketplace link visible?</li><li>Details: can you compare the photos, item ID, SKU, size, or color?</li><li>Freshness: is there a visible update or last-checked note?</li><li>Usability: can you follow the link and understand what the row represents?</li></ol></div></section>
    <div id="categories"><CategoryGrid /></div><section className="content-section"><div className="section-title"><h2>Latest questions</h2><Link href="/questions">See all questions →</Link></div><QuestionList /></section><TopicNav />
  </main><Footer /></>;
}
